run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gosec
    - revive
    - exhaustive
    - noctx
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - funlen
    - gocognit
    - gocritic
    - godot
    - mnd
    - lll
    - misspell
    - nlreturn
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  lll:
    line-length: 140
  funlen:
    lines: 120
    statements: 60
  cyclop:
    max-complexity: 15
  mnd:
    ignored-functions:
      - "time.Duration"
      - "make"
      - "fmt.Sprintf"
      - "float64"

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - funlen
        - mnd
        - dupl
        - lll
    - path: "bootstrap"
      linters:
        - funlen
